# Generated by Django 2.2.6 on 2023-02-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersContact',
            new_name='Contact',
        ),
    ]
